### ISSUE TITLE
When websocket connection is closed, the orderbook should change state.

### ISSUE THREAD

**Issue by pulsecat** [coinbase/coinbase-exchange-node#2]
Currently, the orderbook doesn't change state when connection is lost, so client code doesn't have an opportunity to reopen the connection.
Normally, this problem can be fixed by implementing simple heartbeat functionality, but it seems Coinbase websocket API doesn't yet support ping/pong events.

**Comment by defunctzombie** [comment]
When the connection by the websocket is lost or is some other connection lost?

**Comment by rmm5t** [comment]
Just performing some triage and cleaning up some old issues and pull-requests. Because this repository was deprecated (and will not receive any further updates) in favor of [coinbase/gdax-node](https://github.com/coinbase/gdax-node), if this issue is still something you'd like to see addressed and it is still an issue on gdax-node, we would appreciate you closing this out in favor of starting a discussion at [coinbase/gdax-node](https://github.com/coinbase/gdax-node).

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
