### ISSUE TITLE
create real time sync price

### ISSUE THREAD

**Issue by tallesdantas** [coinbase/coinbase-exchange-node#41]
Hello guys , i'm trying to create a real time app to track the real time bitcoin ask and bid price on coinbase , but every time my source unsync the actual price , can any one tell me what can i do to make it precise with the actual price bid and ask price, here goes my source:

`var CoinbaseExchange = require('coinbase-exchange');
var websocket = new CoinbaseExchange.WebsocketClient();
bid =0;
ask =0;
websocket.on('message', function(data) { 

```
if(data.side == 'sell')
{
    if(data.price > bid )
    bid = data.price;

}else{

    if(data.price > ask)
    ask = data.price;
}

if(data.type == 'match')
{
    ask = data.price;
    bid = data.price;
}

console.log('BID:'+bid+' ASK:'+ask); 
```

});`

i'm really confused of how to track the current bid / ask price , pelase help me

**Comment by rmm5t** [comment]
Just performing some triage and cleaning up some old issues and pull-requests. Because this repository was deprecated (and will not receive any further updates) in favor of [coinbase/gdax-node](https://github.com/coinbase/gdax-node), if this issue is still something you'd like to see addressed and it is still an issue on gdax-node, we would appreciate you closing this out in favor of starting a discussion at [coinbase/gdax-node](https://github.com/coinbase/gdax-node).

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
