### ISSUE TITLE
OrderbookSync does not reconnect when socket connection is lost

### ISSUE THREAD

**Issue by petercerno** [coinbase/coinbase-exchange-node#49]
When the socket connection is lost, OrderbookSync ends up in a stale state (it does not attempt to re-connect and thus also stops updating the underlying orderbook).
One option would be to use / implement a reconnecting-websocket instead of using the standard WebSocket, see e.g.: https://github.com/joewalnes/reconnecting-websocket/blob/master/reconnecting-websocket.js

**Comment by rmm5t** [comment]
Just performing some triage and cleaning up some old issues and pull-requests. Because this repository was deprecated (and will not receive any further updates) in favor of [coinbase/gdax-node](https://github.com/coinbase/gdax-node), if this issue is still something you'd like to see addressed and it is still an issue on gdax-node, we would appreciate you closing this out in favor of starting a discussion at [coinbase/gdax-node](https://github.com/coinbase/gdax-node).

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
