### ISSUE TITLE
OrderbookSync throws error in a callback

### ISSUE THREAD

**Issue by petercerno** [coinbase/coinbase-exchange-node#50]
OrderbookSync throws an error inside an internal callback (when the getProductOrderBook does not successfully fetch the orderbook), see e.g. the line:
    throw 'Failed to load orderbook: ' + err;
in lib/orderbook_sync.js. This error is thrown, for instance, when there is no internet connection.
It is not easy to catch this kind of error in a client application. One option how to fix this problem would be to emit the error (instead of throwing it), e.g.:
    self.emit('error', 'Failed to load orderbook: ' + err);
    return;

**Comment by rmm5t** [comment]
Just performing some triage and cleaning up some old issues and pull-requests. Because this repository was deprecated (and will not receive any further updates) in favor of [coinbase/gdax-node](https://github.com/coinbase/gdax-node), if this issue is still something you'd like to see addressed and it is still an issue on gdax-node, we would appreciate you closing this out in favor of starting a discussion at [coinbase/gdax-node](https://github.com/coinbase/gdax-node).

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
