### ISSUE TITLE
Close Websocket

### ISSUE THREAD

**Issue by ghost** [coinbase/coinbase-exchange-node#51]
I couldn't find any documentation for closing a websocket

I'm using Node.js. A simple example would be opening a websocket, then once the first message is received, close the connection. This would essentially mean "listen until you receive one, and only one message." Is this possible?

```
var CoinbaseExchange = require('coinbase-exchange');
var websocket = new CoinbaseExchange.WebsocketClient();

websocket.on('message', function(data) {
    console.log(data);
    websocket.done();  // or .close();
});
```

**Comment by rmm5t** [comment]
Just performing some triage and cleaning up some old issues and pull-requests. Because this repository was deprecated (and will not receive any further updates) in favor of [coinbase/gdax-node](https://github.com/coinbase/gdax-node), if this issue is still something you'd like to see addressed and it is still an issue on gdax-node, we would appreciate you closing this out in favor of starting a discussion at [coinbase/gdax-node](https://github.com/coinbase/gdax-node).

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
